### PR TITLE
Add support for platform="amazon"

### PR DESCRIPTION
**Pull request by krisalyssa**
It looks like I pulled in a bunch of stuff at the beginning, maybe from not having branched in the right place. The important commits are the ones at the bottom; they all deal with adding support for Amazon EC2's native AMIs.

### CODE REVIEW

**Comment by hedgehog** [comment]
OK when I get a minute I'll see if I can cherry-pick, squash (then review the cumulative changes), rebase then merge these changes. 

Isee you have placed some detail in the readme.md about what has been added - thanks.
This kind of detail is much easier to see when looking at a single commit in github ;)

**Comment by hedgehog** [comment]
Also add yourself to the author list at the bottom of the page.

**Comment by hedgehog** [comment]
Hmm, my git-fu obviously isn't what it needs to be to get a single clean commit for your changes.
I'm going to pull this in the hope it is all good.
I'll need to outline a bullet-proof workflow so we don't keep getting these types of pull reuests - else people will stop volunteering to manage pull-requests, and others will loose confidence because they can't review changes in a coherent way.

Craig do you have any thoughts on a git-workflow that is painless for contributors and maintainers?

**Comment by hedgehog** [comment]
Actually Github seems to make a `merge --squash`:

https://github.com/cookbooks/apache2/commit/a3df1f63f9b35f965b7e538cfe9d89bf8a47c88e

Craig the idea is to try and get your pull request to be a single commit like the above - that way it is much clearer what changes are being made when anyone reviews the code.

**Comment by krisalyssa** [comment]
On Jun 26, 2011, at 16:47 PM, hedgehog wrote:

> Could you add a `qa brach' section to the Readme.md and using a bullet point(s), succinctly outline there what this does? and mention any caveats/requirements/assumptions?

I don't quite understand what you're requesting here. Do you want a section in the readme describing the qa branch, or a new topic branch from the qa branch with a section describing what the "amazon" platform is all about?

## 

Craig S. Cottingham
craig.cottingham@gmail.com
+1-913-826-6896 or Skype me at CraigCottingham

**Comment by krisalyssa** [comment]
On Jun 26, 2011, at 18:24 PM, hedgehog wrote:

> I'll need to outline a bullet-proof workflow so we don't keep getting these types of pull reuests - else people will stop volunteering to manage pull-requests, and others will loose confidence because they can't review changes in a coherent way.

If you're not tired of hearing me apologize, I truly am sorry for causing extra work.

> Craig do you have any thoughts on a git-workflow that is painless for contributors and maintainers?

Here's what I'm trying to do; please let me know if any of it seems unnecessary or doesn't make sense.
1. I keep a branch in my repository named "qa" which is supposed to mirror the branch of the same name in your repository.
2. When I go to start a topic branch, I first pull from your qa into mine. Then I branch off of qa.
3. I commit early and often to my topic branch as I develop.
4. When it's time to send a pull request, I pull from your qa into mine again, then rebase my topic branch on qa, squashing commits.
5. Then I send the pull request.

I think the last couple of pull requests were missing some of these steps (mostly in the rebasing).

## 

Craig S. Cottingham
craig.cottingham@gmail.com
+1-913-826-6896 or Skype me at CraigCottingham

**Comment by hedgehog** [comment]
On Mon, Jun 27, 2011 at 2:32 PM, CraigCottingham
reply@reply.github.com
wrote:

> On Jun 26, 2011, at 16:47 PM, hedgehog wrote:
> 
> > Could you add a `qa brach' section to the Readme.md and using a bullet point(s), succinctly outline there what this does? and mention any caveats/requirements/assumptions?
> 
> I don't quite understand what you're requesting here. Do you want a section in the readme describing the qa branch, or a new topic branch from the qa branch with a section describing what the "amazon" platform is all about?

Forget the readme request when I saw the merged pull-request (i.e. all
the commits as one) I noticed you had added some details to the
readme.  That is fine.

> ## 
> 
> Craig S. Cottingham
> craig.cottingham@gmail.com
> +1-913-826-6896 or Skype me at CraigCottingham
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cookbooks/apache2/pull/3#issuecomment-1445209

## 

πόλλ' οἶδ ἀλώπηξ, ἀλλ' ἐχῖνος ἓν μέγα
[The fox knows many things, but the hedgehog knows one big thing.]
  Archilochus, Greek poet (c. 680 BC – c. 645 BC)
http://hedgehogshiatus.com

**Comment by hedgehog** [comment]
On Mon, Jun 27, 2011 at 2:41 PM, CraigCottingham
reply@reply.github.com
wrote:

> On Jun 26, 2011, at 18:24 PM, hedgehog wrote:
> 
> > I'll need to outline a bullet-proof workflow so we don't keep getting these types of pull reuests - else people will stop volunteering to manage pull-requests, and others will loose confidence because they can't review changes in a coherent way.
> 
> If you're not tired of hearing me apologize, I truly am sorry for causing extra work.

Not a problem, uncovering out a minimal workflow will take some time.

> > Craig do you have any thoughts on a git-workflow that is painless for contributors and maintainers?
> 
> Here's what I'm trying to do; please let me know if any of it seems unnecessary or doesn't make sense.
> 1. I keep a branch in my repository named "qa" which is supposed to mirror the branch of the same name in your repository.

Yep, I think upstream-tracking branch for qa is the way to go, but
simply so that you always have a local copy of that in case the
interwebs are broken when you need to deploy from that branch.

> 1. When I go to start a topic branch, I first pull from your qa into mine. Then I branch off of qa.

Agreed.

> 1. I commit early and often to my topic branch as I develop.
> 2. When it's time to send a pull request, I pull from your qa into mine again, then rebase my topic branch on qa, squashing commits.

Here I think you might try this (untested, origin is the cookbooks repo):
git status
<your topic branch - clean>
git pull --rebase --squash origin qa

But I'm not sure that will always give you a single commit in your
topic branch - see below
While your pull default-site request says it will merge cleanly, I'm nervous.
Simply because when I try the following I get a conflict:

Here is what I tried.

git clone git@github.com:cookbooks/apache2.git
pushd apache2/
git remote add cottingham git://github.com/CraigCottingham/apache2.git
git fetch cottingham
git checkout -b default-site cottingham/default-site
git pull --rebase --squash origin qa

In the last step I get this:

<quote>
From github.com:cookbooks/apache2
- branch            qa         -> FETCH_HEAD
  First, rewinding head to replay your work on top of it...
  Applying: enable default site only on redhat family platforms
  Using index info to reconstruct a base tree...
  Falling back to patching base and 3-way merge...
  Auto-merging metadata.json
  Auto-merging metadata.rb
  Auto-merging recipes/default.rb
  CONFLICT (content): Merge conflict in recipes/default.rb
  Failed to merge in the changes.
  Patch failed at 0001 enable default site only on redhat family platforms

When you have resolved this problem run "git rebase --continue".
If you would prefer to skip this patch, instead run "git rebase --skip".
To restore the original branch and stop rebasing run "git rebase --abort".
You'll notice that I'm just trying to rebase your default branch on to
you qa branch (or at least my checkout of those branches).
</quote>

Could you try the above commands and see if you also get a conflict?
Once they have been resolved, hopefully you'll then have a single
commit in your default-site branch and you can issue a pull request
from there to cookbook/qa and drop your topic branch once the pull
request is merged.
I don't think you'll want to merge your topic branch into your qa
branch and issue a pull request from there, simply because if a pull
request gets rejected your qa branch is not out of sync with the
upstream qa.

Hopefully that makes sense let me know it that doesn't work as expected.

Best wishes.

> 1. Then I send the pull request.
> 
> I think the last couple of pull requests were missing some of these steps (mostly in the rebasing).
> 
> ## 
> 
> Craig S. Cottingham
> craig.cottingham@gmail.com
> +1-913-826-6896 or Skype me at CraigCottingham
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cookbooks/apache2/pull/3#issuecomment-1445231

## 

πόλλ' οἶδ ἀλώπηξ, ἀλλ' ἐχῖνος ἓν μέγα
[The fox knows many things, but the hedgehog knows one big thing.]
  Archilochus, Greek poet (c. 680 BC – c. 645 BC)
http://hedgehogshiatus.com

**Comment by krisalyssa** [comment]
On Jun 27, 2011, at 0:36 AM, hedgehog wrote:

> I don't think you'll want to merge your topic branch into your qa
> branch and issue a pull request from there, simply because if a pull
> request gets rejected your qa branch is not out of sync with the
> upstream qa.

Oh, no, that's not what I meant to say at all. What I was trying to accomplish was to make sure that my topic branch was based on the latest from qa.

## 

Craig S. Cottingham
craig.cottingham@gmail.com
+1-913-826-6896 or Skype me at CraigCottingham

**Comment by hedgehog** [comment]
On Mon, Jun 27, 2011 at 3:40 PM, CraigCottingham
reply@reply.github.com
wrote:

> On Jun 27, 2011, at 0:36 AM, hedgehog wrote:
> 
> > I don't think you'll want to merge your topic branch into your qa
> > branch and issue a pull request from there, simply because if a pull
> > request gets rejected your qa branch is not out of sync with the
> > upstream qa.
> 
> Oh, no, that's not what I meant to say at all. What I was trying to accomplish was to make sure that my topic branch was based on the latest from qa.

OK, I _think the `git pull --rebase --squash <upstream> qa` command
should do that?

> ## 
> 
> Craig S. Cottingham
> craig.cottingham@gmail.com
> +1-913-826-6896 or Skype me at CraigCottingham
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cookbooks/apache2/pull/3#issuecomment-1445352

## 

πόλλ' οἶδ ἀλώπηξ, ἀλλ' ἐχῖνος ἓν μέγα
[The fox knows many things, but the hedgehog knows one big thing.]
  Archilochus, Greek poet (c. 680 BC – c. 645 BC)
http://hedgehogshiatus.com

**Pull request merged**
